/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mydatabaseapp;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author raman
 */
public class examResult extends javax.swing.JFrame {

    Connection myConnection;
    /**
     * Creates new form examResult
     */
    public examResult() {
        initComponents();
    }
    
    public examResult(String uName) throws SQLException {
        initComponents();
        
        textUName.setEditable(false);
        textUName.setText(uName);
        SelectButton();
        
    }
    
    public void SelectButton() throws SQLException{
        DataConnection crteUser=new DataConnection();
        this.myConnection=crteUser.GetConnection();
        Statement selectStmt=myConnection.createStatement();
        String query="select lok from user where username='"+textUName.getText()+"'";
        ResultSet rs=selectStmt.executeQuery(query);
        if(rs.next())
        {
        int lock=Integer.parseInt(rs.getString(1));
        if(lock==0){
            buttonGetResult.setEnabled(false);
            buttonStartExam.setEnabled(true);
        }
        else{
            buttonGetResult.setEnabled(true);
            buttonStartExam.setEnabled(false);
        }
        }
                
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonStartExam = new javax.swing.JButton();
        buttonGetResult = new javax.swing.JButton();
        labelWelcome = new javax.swing.JLabel();
        textUName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonStartExam.setText("Start Exam");
        buttonStartExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartExamActionPerformed(evt);
            }
        });

        buttonGetResult.setText("Get Result");
        buttonGetResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGetResultActionPerformed(evt);
            }
        });

        labelWelcome.setText("Welcome");

        textUName.setText("user");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(labelWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textUName, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonStartExam)
                        .addGap(70, 70, 70)
                        .addComponent(buttonGetResult)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWelcome)
                    .addComponent(textUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonStartExam)
                    .addComponent(buttonGetResult))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStartExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartExamActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try{
        new MCQForm(textUName.getText()).setVisible(true);
        }catch(Exception e){}
    }//GEN-LAST:event_buttonStartExamActionPerformed

    private void buttonGetResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGetResultActionPerformed
        // TODO add your handling code here:
        System.out.println("inside Result Action Performed");
        try{
        new ResultWindow(textUName.getText()).setVisible(true);
        }catch (Exception e){}
    }//GEN-LAST:event_buttonGetResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(examResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(examResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(examResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(examResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new examResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGetResult;
    private javax.swing.JButton buttonStartExam;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JTextField textUName;
    // End of variables declaration//GEN-END:variables
}
